import Foundation

/// Component types
enum ComponentType: String, CaseIterable, Identifiable {
    case accordion = "Accordion"
    case attachment = "Attachment"
    case avatar = "Avatar"
    case badge = "Badge"
    case bottomSheet = "BottomSheet"
    case button = "Button"
    case card = "Card"
    case chip = "Chip"
    case colorPicker = "ColorPicker"
    case emojiPicker = "EmojiPicker"
    case emptyState = "EmptyState"
    case fab = "FloatingActionButton"
    case iconBadge = "IconBadge"
    case iconButton = "IconButton"
    case iconTile = "IconTile"
    case iconPicker = "IconPicker"
    case imagePicker = "ImagePicker"
    case linkCard = "LinkCard"
    case mediaViewer = "MediaViewer"
    case progressBar = "ProgressBar"
    case searchField = "SearchField"
    case secureField = "SecureField"
    case skeleton = "Skeleton"
    case snackbar = "Snackbar"
    case errorState = "ErrorState"
    case insetCallout = "InsetCallout"
    case loadingState = "LoadingState"
    case statDisplay = "StatDisplay"
    case statusBanner = "StatusBanner"
    case statusIndicator = "StatusIndicator"
    case statusPill = "StatusPill"
    case stepIndicator = "StepIndicator"
    case textField = "TextField"
    case timelineRow = "TimelineRow"
    case toast = "Toast"
    case videoPicker = "VideoPicker"
    case videoPlayer = "VideoPlayer"

    var id: String { rawValue }

    var icon: String {
        switch self {
        case .accordion: return "chevron.down.circle.fill"
        case .attachment: return "paperclip"
        case .avatar: return "person.circle.fill"
        case .badge: return "app.badge.fill"
        case .bottomSheet: return "rectangle.bottomhalf.filled"
        case .button: return "hand.tap.fill"
        case .card: return "rectangle.fill"
        case .chip: return "tag.fill"
        case .colorPicker: return "paintpalette.fill"
        case .emojiPicker: return "face.smiling"
        case .emptyState: return "tray"
        case .fab: return "plus.circle.fill"
        case .iconBadge: return "circle.fill"
        case .iconButton: return "heart.circle.fill"
        case .iconTile: return "square.fill"
        case .iconPicker: return "square.grid.3x3"
        case .imagePicker: return "photo.on.rectangle.angled"
        case .linkCard: return "link"
        case .mediaViewer: return "photo.on.rectangle"
        case .progressBar: return "chart.bar.fill"
        case .searchField: return "magnifyingglass"
        case .secureField: return "lock.fill"
        case .skeleton: return "rectangle.dashed"
        case .errorState: return "exclamationmark.triangle.fill"
        case .insetCallout: return "rectangle.inset.filled"
        case .loadingState: return "progress.indicator"
        case .snackbar: return "message.fill"
        case .statDisplay: return "number.circle.fill"
        case .statusBanner: return "exclamationmark.bubble.fill"
        case .statusIndicator: return "checkmark.circle.fill"
        case .statusPill: return "capsule.fill"
        case .stepIndicator: return "ellipsis.circle"
        case .textField: return "textformat.abc"
        case .timelineRow: return "list.bullet.indent"
        case .toast: return "bell.badge.fill"
        case .videoPicker: return "video.badge.plus"
        case .videoPlayer: return "play.rectangle.fill"
        }
    }

    var description: String {
        switch self {
        case .accordion: return "Expandable/collapsible content section"
        case .attachment: return "Thumbnails and horizontal-scrolling strip for selected attachments"
        case .avatar: return "Circular image with initials fallback"
        case .badge: return "Notification dot or count indicator"
        case .bottomSheet: return "Modal sheet from bottom with drag handle"
        case .button: return "3 types: Primary, Secondary, Tertiary"
        case .card: return "Container for grouping related information"
        case .chip: return "Compact labels for status, categories, filters"
        case .colorPicker: return "Select colors from preset palette"
        case .emojiPicker: return "Select emojis by category"
        case .emptyState: return "Placeholder for empty lists and search results"
        case .fab: return "Primary action button on screen"
        case .iconBadge: return "Badge displaying icon on circular background"
        case .iconButton: return "Compact button with icon only"
        case .iconTile: return "Rounded-square semantic icon tile"
        case .iconPicker: return "Select SF Symbols icons"
        case .imagePicker: return "Select images from camera and photo library"
        case .linkCard: return "Card for a URL reference — a source or related link"
        case .mediaViewer: return "Full-screen media viewer opened by a tap"
        case .progressBar: return "Bar for visualizing progress"
        case .searchField: return "Search input with clear and cancel buttons"
        case .secureField: return "Password input with reveal toggle"
        case .skeleton: return "Shimmer placeholder for loading states"
        case .errorState: return "Full-screen error with retry action"
        case .insetCallout: return "Lightly tinted semantic callout block"
        case .loadingState: return "Centered spinner with optional message"
        case .snackbar: return "Display temporary notifications and feedback"
        case .statDisplay: return "Statistics component displaying numbers and units"
        case .statusBanner: return "Inline status messages and alerts"
        case .statusIndicator: return "Single-glyph indicator for task state — pending, running, completed"
        case .statusPill: return "Compact semantic state pill for success, warning, error, and info"
        case .stepIndicator: return "Dot row showing the current position across N steps"
        case .textField: return "Text input field"
        case .timelineRow: return "One row in a chronological feed (activity log)"
        case .toast: return "Auto-dismissing notification from top"
        case .videoPicker: return "Select videos from camera and video library"
        case .videoPlayer: return "Play videos from data or URL"
        }
    }
}
